[project]
name = "dec25-bde-int-crypto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
