apiVersion: 1

datasources:
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://mongodb:27017
    jsonData:
      authType: credentials
      defaultDatabase: crypto_data
    secureJsonData:
      user: admin
      password: password
    editable: true
